version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: speedrail_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/speedrail_development
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: >
      sh -c "
        bundle install &&
        bundle exec rails db:create db:migrate db:seed &&
        bundle exec rails server -b 0.0.0.0
      "

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
